[server]
port = 12345

[programs."ls"]
cmd = "ls -la /home/tgellon/"
num_procs = 2
start_at_launch = false
workdir = "/tmp"
std_out = "/tmp/taskmaster_ls.log"
env = { HELLO = "World", TEST = "Mars" }

[programs.cat]
cmd = "cat /home/tgellon/.zshrc"
start_at_launch = true
std_out = "/tmp/taskmaster_cat.log"
std_err = "/tmp/taskmaster_cat_err.log"
env = { HELLO = "World", TEST = "Mars" }

[programs.echo]
cmd = "echo $HELLO"
start_at_launch = true
workdir = "/tmp"
std_out = "/tmp/taskmaster_echo.log"
env = { HELLO = "World", TEST = "Mars" }

[programs."sleeper"]
cmd = "sleep 30"

[programs."sleeper_failed"]
cmd = "sleep 30"
start_time = 35