[server]
port = 12345

[programs."ls"]
cmd = "ls /home/tgellon/"

[programs."ls".env]
HELLO = "World"
TEST = "Mars"

[programs.cat]
cmd = "cat /home/tgellon/.zshrc"

[programs.cat.env]
HELLO = "World"
TEST = "Mars"
